
# config.yaml for text-to-SQL experiments

# General settings

current_experiment: "C3 Spider Bank Expirement 1"
experiment_description: "Experiment with the whole Bank domain of the Spider dataset."
group: "C3 Zero Shot"
run_id: "1330"

# dataset: "Spider"
dataset: "BIRD"

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0.7
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024
