
# config.yaml for autocorrect experiments

# General settings

current_experiment: "Question Classification few-shot with all examples and gold-query GPT-4"
experiment_description: | 
  Classfying the quality of questions using GPT, input is instructions, questions and the database schema, with gpt-4.
  The questions are classified based on if GPT would like to change the question or not, based on if the instructions could be ambiguous or not.
group: "autocorrect"

# dataset: "Spider"
# dataset: "BIRD"
# dataset: "BIRDFixedFinancial"
# dataset: "BIRDFixedFinancialGoldSQL"
dataset: BIRDCorrectedFinancialGoldAnnotated

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024
