
# config.yaml for autocorrect experiments

# General settings

current_experiment: "Classifying Questions Changes GPT-4 with Database Schema"
experiment_description: | 
  Classfying the quality of questions using GPT, input is instructions, questions and the database schema, with gpt-4-turbo.
  The questions are classified based on if GPT would like to change the question or not, based on if the instructions could be ambiguous or not.
group: "autocrrect"

# dataset: "Spider"
dataset: "BIRD"
# dataset: "BIRDFixedFinancial"
# dataset: "BIRDFixedFinancialGoldSQL"

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-4"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024
