
# config.yaml for text-to-SQL experiments

# General settings

log_experiment: true

current_experiment: "zero_shot_experiment_0"
project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

current_prompt: |
  Database schema in the form of CREATE_TABLE statements:
  {database_schema}

  Using valid SQL, answer the following question based on the tables provided above.

  Hint helps you to write the correct sqlite SQL query.
  Question: {question}
  Hint: {evidence}
  DO NOT return anything else except the SQL statement.

    
# Domain settings
domains: 
  - financial
#  - retail_world
#  - retails
#  - car_retails

difficulties: 
  - simple
  - moderate
  - challenging

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024




